// Build a kid-safe, length-filtered dictionary from `an-array-of-english-words`.
// Output: src/lib/wordshake-dict-data.ts (committed; regenerate with `node scripts/build-dict.mjs`).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const words = require("an-array-of-english-words");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.resolve(__dirname, "..", "src", "lib", "wordshake-dict-data.ts");

const MIN_LEN = 2;
const MAX_LEN = 8;

// Small kid-unsafe block list. Substring match against the lowercased word.
// Conservative — better to drop a few innocent words than show anything inappropriate.
const BLOCK_SUBSTRINGS = [
  "fuck", "shit", "bitch", "asshole", "damn", "dick", "cock", "cunt",
  "piss", "porn", "rape", "slut", "whore", "nigg", "fag", "tit", "boob",
  "wank", "anal", "anus", "arse", "bastard", "bollock", "bugger", "crap",
  "kill", "murder", "suicide", "nazi", "hitler", "drug", "weed", "heroin",
  "cocaine", "vagina", "penis", "scrotum", "semen", "ejacul",
];

function isBlocked(w) {
  for (const b of BLOCK_SUBSTRINGS) if (w.includes(b)) return true;
  return false;
}

const filtered = words.filter((w) => {
  if (w.length < MIN_LEN || w.length > MAX_LEN) return false;
  if (!/^[a-z]+$/.test(w)) return false;
  if (isBlocked(w)) return false;
  return true;
});

// Always include challenge target words even if length>MAX_LEN.
const EXTRAS = [
  "feather", "rainbow", "explore", "balloon", "sparkle", "journey", "book",
];
const set = new Set(filtered);
for (const e of EXTRAS) set.add(e);
const finalList = Array.from(set).sort();

const banner = `// AUTO-GENERATED by scripts/build-dict.mjs. Do not edit by hand.
// Source: an-array-of-english-words (filtered to length ${MIN_LEN}-${MAX_LEN}, kid-safe).
// Total words: ${finalList.length}.
`;

const body =
  banner +
  `\nexport const WORDSHAKE_WORDS: readonly string[] = ` +
  JSON.stringify(finalList) +
  `;\n`;

fs.writeFileSync(outFile, body);
console.log(`Wrote ${finalList.length} words to ${outFile} (${(fs.statSync(outFile).size / 1024).toFixed(0)} KB)`);
